import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any

def generate_pdf_report(
    summary_data: Dict[str, Any],
    abc_data: Dict[str, Any],
    comparison_data: Dict[str, Any],
    output_filepath: str
) -> str:
    """
    Generates a professional executive PDF report containing executive summary,
    KPIs, ABC inventory classification, model comparison metrics, and business recommendations.
    """
    doc = SimpleDocTemplate(
        output_filepath,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0f172a'),
        alignment=1,  # Center
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#64748b'),
        alignment=1,
        spaceAfter=25
    )
    
    heading2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#0284c7'),
        spaceBefore=15,
        spaceAfter=8
    )
    
    body_style = ParagraphStyle(
        'BodyCustom',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    story = []

    # Title & Header
    story.append(Paragraph("Industrial Material Consumption Forecasting System", title_style))
    story.append(Paragraph("Executive Forecast & Inventory Analysis Report | Generated by AI Platform", subtitle_style))
    story.append(Spacer(1, 10))

    # Executive Summary Section
    story.append(Paragraph("1. Executive Summary & KPIs", heading2_style))
    qty_stats = summary_data.get('quantity', {})
    amt_stats = summary_data.get('amount', {})
    
    kpi_data = [
        ["Metric", "Quantity (KG)", "Monetary Amount (₹)"],
        ["Total Overall", f"{qty_stats.get('total', 0):,.2f}", f"₹ {amt_stats.get('total', 0):,.2f}"],
        ["Monthly Average", f"{qty_stats.get('mean', 0):,.2f}", f"₹ {amt_stats.get('mean', 0):,.2f}"],
        ["Maximum Single Month", f"{qty_stats.get('max', 0):,.2f}", f"₹ {amt_stats.get('max', 0):,.2f}"],
        ["Minimum Single Month", f"{qty_stats.get('min', 0):,.2f}", f"₹ {amt_stats.get('min', 0):,.2f}"],
        ["Standard Deviation", f"{qty_stats.get('std_dev', 0):,.2f}", f"₹ {amt_stats.get('std_dev', 0):,.2f}"]
    ]
    
    kpi_table = Table(kpi_data, colWidths=[180, 170, 170])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 15))

    # ABC Analysis Section
    story.append(Paragraph("2. ABC Inventory Classification", heading2_style))
    abc_summary = abc_data.get('summary', {})
    
    abc_table_data = [
        ["Class", "Criteria", "Item Count", "% of Items", "Total Value (₹)", "% of Value"],
        ["Class A", "Top 70% Value", str(abc_summary.get('A', {}).get('item_count', 0)), f"{abc_summary.get('A', {}).get('item_percentage', 0)}%", f"₹ {abc_summary.get('A', {}).get('total_value', 0):,.2f}", f"{abc_summary.get('A', {}).get('value_percentage', 0)}%"],
        ["Class B", "Next 20% Value", str(abc_summary.get('B', {}).get('item_count', 0)), f"{abc_summary.get('B', {}).get('item_percentage', 0)}%", f"₹ {abc_summary.get('B', {}).get('total_value', 0):,.2f}", f"{abc_summary.get('B', {}).get('value_percentage', 0)}%"],
        ["Class C", "Remaining 10%", str(abc_summary.get('C', {}).get('item_count', 0)), f"{abc_summary.get('C', {}).get('item_percentage', 0)}%", f"₹ {abc_summary.get('C', {}).get('total_value', 0):,.2f}", f"{abc_summary.get('C', {}).get('value_percentage', 0)}%"],
    ]
    
    abc_table = Table(abc_table_data, colWidths=[60, 90, 80, 80, 130, 80])
    abc_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0284c7')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
    ]))
    story.append(abc_table)
    story.append(Spacer(1, 15))

    # Model Evaluation Comparison Section
    story.append(Paragraph("3. AI Forecasting Model Performance Leaderboard", heading2_style))
    metrics_list = comparison_data.get('metrics', [])
    best_model = comparison_data.get('best_model', 'N/A')
    
    comp_table_data = [["Model Name", "MAE (KG)", "RMSE (KG)", "MAPE (%)", "R² Score", "Status"]]
    for m in metrics_list:
        is_best = "★ BEST" if m['model'] == best_model else ""
        comp_table_data.append([
            m['model'],
            f"{m['mae']:,.2f}",
            f"{m['rmse']:,.2f}",
            f"{m['mape']:.2f}%",
            f"{m['r2_score']:.4f}",
            is_best
        ])
        
    comp_table = Table(comp_table_data, colWidths=[90, 95, 95, 80, 80, 80])
    comp_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#334155')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
    ]))
    story.append(comp_table)
    story.append(Spacer(1, 15))

    # Strategic Recommendations Section
    story.append(Paragraph("4. Business Recommendations & Action Plan", heading2_style))
    story.append(Paragraph(f"<b>Optimal Forecasting Engine:</b> <b>{best_model}</b> achieved the lowest MAE error rate and is recommended for operational planning.", body_style))
    story.append(Paragraph("<b>Class A Materials Control:</b> Enforce tight inventory buffers and weekly consumption monitoring.", body_style))
    story.append(Paragraph("<b>Class B & C Automation:</b> Implement automated reorder points and bi-weekly supplier schedules.", body_style))

    doc.build(story)
    return output_filepath
